defaults:
  - _self_
  - tasks: forecasting
  - models: naive_forecast #mlp
  - runner: base_runner
  - data: ett_dataset
  - random_seed: basic
  - optimizer: base

sanity_run: False
experiment_name: ett_mlp_forecasting

train:
  device: cuda
  epochs: 5
  early_stopping:
    patience: 3

eval:
  init:
    main_val_metric: loss
    key_val_metric: mse

test: {}

study_name: test_pipeline

hydra:
  run:
    dir: ./outputs/${study_name}
  sweep:
    dir: multirun/timemixer_noise_dependence
    subdir: run_${hydra.job.num}
  sweeper:
    params:
      random_seed.seed: 41, 42, 43
